## Machine Learning Assignment: Logistic Regression
### Tic-Tac-Toe game
Refentse Bane: 1390445

Motheo Sekgetho: 1432706

Michael Nyembe:

### Data Description
This database encodes the complete set of possible board configurations at the end of tic-tac-toe games, where "x" is assumed to have played first. The target concept is "win for x" (i.e., true when "x" has one of 8 possible ways to create a "three-in-a-row").

Attribute Information:

top-left-square: {x,o,b}

top-middle-square: {x,o,b}

top-right-square: {x,o,b}

middle-left-square: {x,o,b}

middle-middle-square: {x,o,b}

middle-right-square: {x,o,b}

bottom-left-square: {x,o,b}

bottom-middle-square: {x,o,b}

bottom-right-square: {x,o,b}

Class: {positive,negative}

What we are trying to predict: A win for x

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics
from sklearn.model_selection import cross_val_score

## Description of structure

In [5]:
data = pd.read_csv("tic-tac-toe.data", sep = ",")
data.rename(columns={'x': 'top-left-square', 'x.1': 'top-middle-square', 'x.2': 'top-right-square','x.3': 'middle-left-square', 'o': 'middle-middle-square', 'o.1' : 'middle-right-square', 'x.4' : 'bottom-left-square', 'o.2' : 'bottom-middle-square', 'o.3':'bottom-right-square','positive' : 'outcome'},inplace=True)

#### Features & Class

In [6]:
data.head(4)

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,outcome
0,x,x,x,x,o,o,o,x,o,positive
1,x,x,x,x,o,o,o,o,x,positive
2,x,x,x,x,o,o,o,b,b,positive
3,x,x,x,x,o,o,b,o,b,positive

In [7]:
data_new = pd.get_dummies(data.iloc[:,0:10])

In [8]:
data_new.head(7)

,top-left-square_b,top-left-square_o,top-left-square_x,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-square_b,top-right-square_o,top-right-square_x,middle-left-square_b,...,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x,outcome_negative,outcome_positive
0,0,0,1,0,0,1,0,0,1,0,...,1,0,0,0,1,0,1,0,0,1
1,0,0,1,0,0,1,0,0,1,0,...,1,0,0,1,0,0,0,1,0,1
2,0,0,1,0,0,1,0,0,1,0,...,1,0,1,0,0,1,0,0,0,1
3,0,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
4,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,0,1,0,0,1
5,0,0,1,0,0,1,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
6,0,0,1,0,0,1,0,0,1,0,...,1,0,1,0,0,0,1,0,0,1

In [9]:
data_final = pd.concat([data_new],axis=1)

#### Training & Test data split

In [10]:
trainSet, testSet = train_test_split(data_final,test_size = 0.33)

In [11]:
trainSet.head(7)

,top-left-square_b,top-left-square_o,top-left-square_x,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-square_b,top-right-square_o,top-right-square_x,middle-left-square_b,...,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x,outcome_negative,outcome_positive
823,0,1,0,0,1,0,0,1,0,0,...,0,1,0,1,0,0,0,1,1,0
115,0,0,1,0,1,0,0,0,1,0,...,0,1,1,0,0,1,0,0,0,1
946,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,1,0,0,1,1,0
392,0,1,0,0,1,0,0,0,1,1,...,0,1,1,0,0,0,1,0,0,1
165,0,0,1,0,1,0,0,1,0,0,...,0,1,1,0,0,0,0,1,0,1
334,0,1,0,0,0,1,0,1,0,0,...,0,1,0,0,1,0,0,1,0,1
721,0,0,1,1,0,0,0,1,0,0,...,1,0,0,0,1,0,0,1,1,0

In [12]:
x_trainSet = trainSet.iloc[:,:-1]
y_trainSet = trainSet.iloc[:,-1]
x_testSet = testSet.iloc[:,:-1]
y_testSet = testSet.iloc[:,-1]

#### Description of Training & Test data

In [13]:
print('training dataset : ')
print('{:_<24s} = {:d}'.format('number of samples', y_trainSet.shape[0]))
print('{:_<24s} = {:d}'.format('number of wins for x', np.sum(y_trainSet == 1)))
print('{:_<24s} = {:d}'.format('number of wins for o', np.sum(y_trainSet == 0)))

training dataset :
number of samples_______ = 641
number of wins for x____ = 420
number of wins for o____ = 221

In [14]:
print('testing dataset : ')
print('{:_<24s} = {:d}'.format('number of samples', y_testSet.shape[0]))
print('{:_<24s} = {:d}'.format('number of wins for x', np.sum(y_testSet == 1)))
print('{:_<24s} = {:d}'.format('number of wins for 0', np.sum(y_testSet == 0)))

testing dataset :
number of samples_______ = 316
number of wins for x____ = 205
number of wins for 0____ = 111

In [15]:
x_trainSet.head(7)

,top-left-square_b,top-left-square_o,top-left-square_x,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-square_b,top-right-square_o,top-right-square_x,middle-left-square_b,...,bottom-left-square_b,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x,outcome_negative
823,0,1,0,0,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,1
115,0,0,1,0,1,0,0,0,1,0,...,0,0,1,1,0,0,1,0,0,0
946,0,0,1,0,1,0,0,0,1,0,...,0,1,0,0,0,1,0,0,1,1
392,0,1,0,0,1,0,0,0,1,1,...,0,0,1,1,0,0,0,1,0,0
165,0,0,1,0,1,0,0,1,0,0,...,0,0,1,1,0,0,0,0,1,0
334,0,1,0,0,0,1,0,1,0,0,...,0,0,1,0,0,1,0,0,1,0
721,0,0,1,1,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,1,1

 We use outcome_positive as our class.
 
 If we get a 1,we know that it is positive hence x wins
 
 If we get a 0,we know that it is 1 for negative hence x losses

In [16]:
y_trainSet.head(7)

823    0
115    1
946    0
392    1
165    1
334    1
721    0
Name: outcome_positive, dtype: uint8

### Normalization

In [26]:
x_trainSet = (x_trainSet - np.mean(x_trainSet, axis=0)) /np.std(x_trainSet, axis=0)
x_testSet = (x_testSet - np.mean(x_trainSet, axis=0)) /np.std(x_trainSet, axis=0)

Augment training and testing for fast matrix operation

In [28]:
x_trainSet_aug = np.hstack((np.ones((x_trainSet.shape[0],1)), x_trainSet))
x_testSet_aug = np.hstack((np.ones((x_testSet.shape[0],1)), x_testSet))

## Logistic Regression Algorithm

### Sigmoid Function

In [17]:
def h(x, weight):
    z = np.dot(x, weight.T)
    h = 1.0 / (1.0 + np.exp(-z))
    return h

### Cost Function

In [18]:
def cost(x,y,weight):
    N = y.shape[0]
    #Logistic Likelihood
    loglike = 1.0/(2*N) * np.sum((h(x,weight)-y)**2)
    return loglike

### Gradient Descent

In [127]:
def logisticRegression(x,y,weight,learn_rate,reg,maxIteration = 1000):
    y = y[:,np.newaxis]
    N = y.shape[0]
    i = 0
    while True:
        print('{:>2d} loss = {:>8f}'.format(i, cost(x,y,weight)))
        weight_prev = weight.copy()
        error = (h(x,weight)- y)
        weight = weight - (learn_rate*1.0)/N * np.sum(error * x, axis=0)
        i=i+1
        if (np.max(np.abs(weight - weight_prev)) < reg) or (i > maxIteration):
            break
    return weight

Learn parameters based off random parameter vector generated

In [128]:
weight = np.random.randn(1, x_trainSet_aug.shape[1])
weight = logisticRegression(x_trainSet_aug, y_trainSet, weight,0.1,0.02)

 0 loss = 0.172510
 1 loss = 0.170642
 2 loss = 0.168752
 3 loss = 0.166840
 4 loss = 0.164905
 5 loss = 0.162948
 6 loss = 0.160969
 7 loss = 0.158969
 8 loss = 0.156949
 9 loss = 0.154911
10 loss = 0.152857
11 loss = 0.150790
12 loss = 0.148711
13 loss = 0.146625
14 loss = 0.144532
15 loss = 0.142437
16 loss = 0.140340
17 loss = 0.138245
18 loss = 0.136153
19 loss = 0.134065
20 loss = 0.131982
21 loss = 0.129904
22 loss = 0.127831
23 loss = 0.125762
24 loss = 0.123697
25 loss = 0.121633
26 loss = 0.119571
27 loss = 0.117508
28 loss = 0.115444
29 loss = 0.113378
30 loss = 0.111309
31 loss = 0.109236
32 loss = 0.107161
33 loss = 0.105084
34 loss = 0.103004
35 loss = 0.100923
36 loss = 0.098843
37 loss = 0.096765
38 loss = 0.094690
39 loss = 0.092621
40 loss = 0.090559
41 loss = 0.088505
42 loss = 0.086463
43 loss = 0.084433
44 loss = 0.082418
45 loss = 0.080419
46 loss = 0.078436
47 loss = 0.076473
48 loss = 0.074529
49 loss = 0.072605
50 loss = 0.070704
51 loss = 0.068825
52 loss = 0.066969

Test classifier performance

In [129]:
y_predict = (h(x_testSet_aug, weight) >= 0.5) [:,0]
test_error = np.sum(y_testSet != y_predict) / y_testSet.shape[0]
print('Logistic Regression test error = {:.4f}'.format(test_error))

Logistic Regression test error = 0.1835

### Confusion Matrix

In [120]:
print(metrics.confusion_matrix(y_testSet, y_predict))

[[111   0]
 [203   2]]

### What happens when we change learn rate & regularization

Set Learn rate = 0.1

Set Regularization = 0.01

In [150]:
weight = np.random.randn(1, x_trainSet_aug.shape[1])
weight = logisticRegression(x_trainSet_aug, y_trainSet, weight,0.1,0.01)

 0 loss = 0.188079
 1 loss = 0.186270
 2 loss = 0.184456
 3 loss = 0.182636
 4 loss = 0.180812
 5 loss = 0.178982
 6 loss = 0.177149
 7 loss = 0.175311
 8 loss = 0.173469
 9 loss = 0.171623
10 loss = 0.169774
11 loss = 0.167922
12 loss = 0.166066
13 loss = 0.164207
14 loss = 0.162345
15 loss = 0.160480
16 loss = 0.158612
17 loss = 0.156741
18 loss = 0.154867
19 loss = 0.152989
20 loss = 0.151108
21 loss = 0.149225
22 loss = 0.147337
23 loss = 0.145447
24 loss = 0.143553
25 loss = 0.141656
26 loss = 0.139756
27 loss = 0.137852
28 loss = 0.135945
29 loss = 0.134034
30 loss = 0.132119
31 loss = 0.130201
32 loss = 0.128279
33 loss = 0.126354
34 loss = 0.124425
35 loss = 0.122493
36 loss = 0.120558
37 loss = 0.118620
38 loss = 0.116679
39 loss = 0.114737
40 loss = 0.112794
41 loss = 0.110850
42 loss = 0.108906
43 loss = 0.106963
44 loss = 0.105022
45 loss = 0.103084
46 loss = 0.101151
47 loss = 0.099222
48 loss = 0.097300
49 loss = 0.095386
50 loss = 0.093481
51 loss = 0.091586
52 loss = 0.089703
53 loss = 0.087832
54 loss = 0.085976
55 loss = 0.084135
56 loss = 0.082311
57 loss = 0.080504
58 loss = 0.078716
59 loss = 0.076949
60 loss = 0.075203
61 loss = 0.073479
62 loss = 0.071778
63 loss = 0.070101
64 loss = 0.068449
65 loss = 0.066823
66 loss = 0.065223
67 loss = 0.063650
68 loss = 0.062104
69 loss = 0.060586
70 loss = 0.059095
71 loss = 0.057633
72 loss = 0.056199
73 loss = 0.054793
74 loss = 0.053416
75 loss = 0.052068
76 loss = 0.050747
77 loss = 0.049455
78 loss = 0.048191
79 loss = 0.046955
80 loss = 0.045746
81 loss = 0.044565
82 loss = 0.043412
83 loss = 0.042285
84 loss = 0.041185
85 loss = 0.040111
86 loss = 0.039063
87 loss = 0.038041
88 loss = 0.037045
89 loss = 0.036073
90 loss = 0.035126
91 loss = 0.034203
92 loss = 0.033305
93 loss = 0.032429
94 loss = 0.031577
95 loss = 0.030747
96 loss = 0.029940
97 loss = 0.029154
98 loss = 0.028390
99 loss = 0.027646
100 loss = 0.026923
101 loss = 0.026220
102 loss = 0.025537
103 loss = 0.024873
104 loss = 0.024227
105 loss = 0.023600
106 loss = 0.022990
107 loss = 0.022398
108 loss = 0.021822
109 loss = 0.021263
110 loss = 0.020720

In [151]:
y_predict = (h(x_testSet_aug, weight) >= 0.5) [:,0]
test_error = np.sum(y_testSet != y_predict) / y_testSet.shape[0]
print('Logistic Regression test error = {:.4f}'.format(test_error))

Logistic Regression test error = 0.1646

In [152]:
weight = np.random.randn(1, x_trainSet_aug.shape[1])
weight = logisticRegression(x_trainSet_aug, y_trainSet, weight,0.1,0.03)

 0 loss = 0.235664
 1 loss = 0.232879
 2 loss = 0.230027
 3 loss = 0.227106
 4 loss = 0.224118
 5 loss = 0.221063
 6 loss = 0.217941
 7 loss = 0.214753
 8 loss = 0.211500
 9 loss = 0.208180
10 loss = 0.204796
11 loss = 0.201350
12 loss = 0.197843
13 loss = 0.194278
14 loss = 0.190660
15 loss = 0.186994
16 loss = 0.183284
17 loss = 0.179536
18 loss = 0.175756
19 loss = 0.171947
20 loss = 0.168116
21 loss = 0.164266
22 loss = 0.160403
23 loss = 0.156529
24 loss = 0.152650
25 loss = 0.148769
26 loss = 0.144891
27 loss = 0.141020
28 loss = 0.137161
29 loss = 0.133318
30 loss = 0.129496
31 loss = 0.125699
32 loss = 0.121932
33 loss = 0.118201
34 loss = 0.114509

In [153]:
y_predict = (h(x_testSet_aug, weight) >= 0.5) [:,0]
test_error = np.sum(y_testSet != y_predict) / y_testSet.shape[0]
print('Logistic Regression test error = {:.4f}'.format(test_error))

Logistic Regression test error = 0.3101

Set Learn Rate = 0.1

Set Regularization = 0.04

In [154]:
weight = np.random.randn(1, x_trainSet_aug.shape[1])
weight = logisticRegression(x_trainSet_aug, y_trainSet, weight,0.1,0.04)

 0 loss = 0.257144
 1 loss = 0.252792
 2 loss = 0.248459
 3 loss = 0.244139
 4 loss = 0.239825
 5 loss = 0.235514
 6 loss = 0.231198
 7 loss = 0.226875
 8 loss = 0.222540
 9 loss = 0.218189
10 loss = 0.213822
11 loss = 0.209436
12 loss = 0.205030
13 loss = 0.200605
14 loss = 0.196162
15 loss = 0.191701
16 loss = 0.187225
17 loss = 0.182736
18 loss = 0.178237
19 loss = 0.173732
20 loss = 0.169224
21 loss = 0.164717
22 loss = 0.160216
23 loss = 0.155726

In [155]:
y_predict = (h(x_testSet_aug, weight) >= 0.5) [:,0]
test_error = np.sum(y_testSet != y_predict) / y_testSet.shape[0]
print('Logistic Regression test error = {:.4f}'.format(test_error))

Logistic Regression test error = 0.6487

Set Learn Rate = 0.1

Set Regularization = 0.05

In [158]:
weight = np.random.randn(1, x_trainSet_aug.shape[1])
weight = logisticRegression(x_trainSet_aug, y_trainSet, weight,0.1,0.04)

 0 loss = 0.217297
 1 loss = 0.213539
 2 loss = 0.209726
 3 loss = 0.205865
 4 loss = 0.201964
 5 loss = 0.198030
 6 loss = 0.194073
 7 loss = 0.190099
 8 loss = 0.186116
 9 loss = 0.182129
10 loss = 0.178145
11 loss = 0.174168
12 loss = 0.170202
13 loss = 0.166251
14 loss = 0.162318
15 loss = 0.158405

In [159]:
y_predict = (h(x_testSet_aug, weight) >= 0.5) [:,0]
test_error = np.sum(y_testSet != y_predict) / y_testSet.shape[0]
print('Logistic Regression test error = {:.4f}'.format(test_error))

Logistic Regression test error = 0.3259