## Machine Learning Assignment: Logistic Regression
### Tic-Tac-Toe game
Refentse Bane: 1390445

Motheo Sekgetho: 

Michael Nyembe:

### Data Description
This database encodes the complete set of possible board configurations at the end of tic-tac-toe games, where "x" is assumed to have played first. The target concept is "win for x" (i.e., true when "x" has one of 8 possible ways to create a "three-in-a-row").

Attribute Information:

top-left-square: {x,o,b}

top-middle-square: {x,o,b}

top-right-square: {x,o,b}

middle-left-square: {x,o,b}

middle-middle-square: {x,o,b}

middle-right-square: {x,o,b}

bottom-left-square: {x,o,b}

bottom-middle-square: {x,o,b}

bottom-right-square: {x,o,b}

Class: {positive,negative}

What we are trying to predict: A win for x

In [44]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics
from sklearn.model_selection import cross_val_score

## Description of structure

In [3]:
data = pd.read_csv("tic-tac-toe.data", sep = ",")
data.rename(columns={'x': 'top-left-square', 'x.1': 'top-middle-square', 'x.2': 'top-right-square','x.3': 'middle-left-square', 'o': 'middle-middle-square', 'o.1' : 'middle-right-square', 'x.4' : 'bottom-left-square', 'o.2' : 'bottom-middle-square', 'o.3':'bottom-right-square','positive' : 'outcome'},inplace=True)

#### Features & Class

In [46]:
data.head(4)

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,outcome
0,x,x,x,x,o,o,o,x,o,positive
1,x,x,x,x,o,o,o,o,x,positive
2,x,x,x,x,o,o,o,b,b,positive
3,x,x,x,x,o,o,b,o,b,positive

In [6]:
data_new = pd.get_dummies(data.iloc[:,0:10])

In [8]:
data_new.head(7)

,top-left-square_b,top-left-square_o,top-left-square_x,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-square_b,top-right-square_o,top-right-square_x,middle-left-square_b,...,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x,outcome_negative,outcome_positive
0,0,0,1,0,0,1,0,0,1,0,...,1,0,0,0,1,0,1,0,0,1
1,0,0,1,0,0,1,0,0,1,0,...,1,0,0,1,0,0,0,1,0,1
2,0,0,1,0,0,1,0,0,1,0,...,1,0,1,0,0,1,0,0,0,1
3,0,0,1,0,0,1,0,0,1,0,...,0,0,0,1,0,1,0,0,0,1
4,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,0,1,0,0,1
5,0,0,1,0,0,1,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
6,0,0,1,0,0,1,0,0,1,0,...,1,0,1,0,0,0,1,0,0,1

In [9]:
data_final = pd.concat([data_new],axis=1)

#### Training & Test data split

In [10]:
trainSet, testSet = train_test_split(data_final,test_size = 0.33)

In [11]:
trainSet.head(7)

,top-left-square_b,top-left-square_o,top-left-square_x,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-square_b,top-right-square_o,top-right-square_x,middle-left-square_b,...,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x,outcome_negative,outcome_positive
478,0,1,0,1,0,0,1,0,0,0,...,0,1,0,0,1,0,0,1,0,1
942,0,0,1,0,0,1,0,1,0,0,...,0,1,0,0,1,0,1,0,1,0
385,0,1,0,0,1,0,0,0,1,0,...,0,1,0,0,1,1,0,0,0,1
902,1,0,0,0,0,1,0,1,0,1,...,0,1,1,0,0,0,1,0,1,0
396,0,1,0,0,1,0,0,0,1,1,...,0,1,1,0,0,0,0,1,0,1
347,0,1,0,0,0,1,1,0,0,0,...,1,0,0,0,1,1,0,0,0,1
120,0,0,1,0,1,0,0,0,1,0,...,0,1,0,1,0,0,1,0,0,1

In [13]:
x_trainSet = trainSet.iloc[:,:-1]
y_trainSet = trainSet.iloc[:,-1]
x_testSet = testSet.iloc[:,:-1]
y_testSet = testSet.iloc[:,-1]

#### Description of Training & Test data

In [14]:
print('training dataset : ')
print('{:_<24s} = {:d}'.format('number of samples', y_trainSet.shape[0]))
print('{:_<24s} = {:d}'.format('number of wins for x', np.sum(y_trainSet == 1)))
print('{:_<24s} = {:d}'.format('number of wins for o', np.sum(y_trainSet == 0)))

training dataset :
number of samples_______ = 641
number of wins for x____ = 402
number of wins for o____ = 239

In [15]:
print('testing dataset : ')
print('{:_<24s} = {:d}'.format('number of samples', y_testSet.shape[0]))
print('{:_<24s} = {:d}'.format('number of wins for x', np.sum(y_testSet == 1)))
print('{:_<24s} = {:d}'.format('number of wins for 0', np.sum(y_testSet == 0)))

testing dataset :
number of samples_______ = 316
number of wins for x____ = 223
number of wins for 0____ = 93

In [45]:
x_trainSet.head(7)

,top-left-square_b,top-left-square_o,top-left-square_x,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-square_b,top-right-square_o,top-right-square_x,middle-left-square_b,...,bottom-left-square_b,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x,outcome_negative
760,0,1,0,0,0,1,0,0,1,0,...,0,1,0,0,0,1,0,0,1,1
29,0,0,1,0,0,1,0,0,1,0,...,0,1,0,1,0,0,0,0,1,0
691,0,0,1,0,1,0,0,1,0,0,...,0,1,0,1,0,0,0,0,1,1
61,0,0,1,0,0,1,0,0,1,1,...,1,0,0,1,0,0,1,0,0,0
295,0,1,0,0,0,1,0,0,1,0,...,0,1,0,0,0,1,0,1,0,0
538,1,0,0,0,1,0,0,0,1,0,...,0,0,1,1,0,0,0,0,1,0
906,1,0,0,0,0,1,0,1,0,1,...,0,0,1,0,0,1,0,1,0,1

 We use outcome_positive as our class.
 
 If we get a 1,we know that it is positive hence x wins
 
 If we get a 0,we know that it is 1 for negative hence x losses

In [17]:
y_trainSet.head(7)

478    1
942    0
385    1
902    0
396    1
347    1
120    1
Name: outcome_positive, dtype: uint8

In [18]:
def h(x, weight):
    z = np.dot(x, weight.T)
    h = 1.0 / (1.0 + np.exp(-z))
    return h

In [19]:
def cost(x,y,weight):
    #z = np.dot(x, weight.T)
    N = y.shape[0]
    loglike = 1.0/(2*N) * np.sum((h(x,weight)-y)**2)
    #loglike = np.sum(y*z - np.log(1+np.exp(z)))
    return loglike

In [20]:
def logisticRegression(x,y,weight,learn_rate = 0.1,epsilon = 0.02,maxIteration = 1000):
    y = y[:,np.newaxis]
    N = y.shape[0]
    i = 0
    while True:
        print('iteration{:>2d}, loss = {:>8f}'.format(i, cost(x,y,weight)))
        weight_prev = weight.copy()
        error = (h(x,weight)- y)
        weight = weight - (learn_rate*1.0)/N * np.sum(error * x, axis=0)
        i=i+1
        if (np.max(np.abs(weight - weight_prev)) < epsilon) or (i > maxIteration):
            break
    return weight

In [21]:

x_trainSet = (x_trainSet - np.mean(x_trainSet, axis=0)) /np.std(x_trainSet, axis=0)
x_testSet = (x_testSet - np.mean(x_trainSet, axis=0)) /np.std(x_trainSet, axis=0)

In [22]:
x_trainSet_aug = np.hstack((np.ones((x_trainSet.shape[0],1)), x_trainSet))
x_testSet_aug = np.hstack((np.ones((x_testSet.shape[0],1)), x_testSet))

In [23]:
weight = np.random.randn(1, x_trainSet_aug.shape[1])
weight = logisticRegression(x_trainSet_aug, y_trainSet, weight)

iteration 0, loss = 0.231241
iteration 1, loss = 0.226557
iteration 2, loss = 0.221775
iteration 3, loss = 0.216908
iteration 4, loss = 0.211970
iteration 5, loss = 0.206970
iteration 6, loss = 0.201923
iteration 7, loss = 0.196839
iteration 8, loss = 0.191729
iteration 9, loss = 0.186605
iteration10, loss = 0.181477
iteration11, loss = 0.176354
iteration12, loss = 0.171245
iteration13, loss = 0.166159
iteration14, loss = 0.161101
iteration15, loss = 0.156080
iteration16, loss = 0.151101
iteration17, loss = 0.146169
iteration18, loss = 0.141292
iteration19, loss = 0.136474
iteration20, loss = 0.131722
iteration21, loss = 0.127042
iteration22, loss = 0.122438
iteration23, loss = 0.117918
iteration24, loss = 0.113487
iteration25, loss = 0.109152
iteration26, loss = 0.104916
iteration27, loss = 0.100785
iteration28, loss = 0.096764
iteration29, loss = 0.092855
iteration30, loss = 0.089063
iteration31, loss = 0.085388
iteration32, loss = 0.081833
iteration33, loss = 0.078398
iteration34, loss = 0.075083
iteration35, loss = 0.071890
iteration36, loss = 0.068815
iteration37, loss = 0.065859
iteration38, loss = 0.063020
iteration39, loss = 0.060295
iteration40, loss = 0.057682
iteration41, loss = 0.055179
iteration42, loss = 0.052782
iteration43, loss = 0.050489
iteration44, loss = 0.048297

In [24]:
y_predict = (h(x_testSet_aug, weight) >= 0.5) [:,0]
test_error = np.sum(y_testSet != y_predict) / y_testSet.shape[0]
print('logistic regression test error = {:.4f}'.format(test_error))

logistic regression test error = 0.3165

In [25]:
from sklearn import metrics
from sklearn.model_selection import cross_val_score

In [27]:
print(metrics.confusion_matrix(y_testSet, y_predict))

[[ 91   2]
 [ 98 125]]