In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
from sklearn import preprocessing

In [30]:
data = pd.read_csv("tic-tac-toe.data", sep = ",")
data.rename(columns={'x': 'top-left-square', 'x.1': 'top-middle-square', 'x.2': 'top-right-square','x.3': 'middle-left-square', 'o': 'middle-middle-square', 'o.1' : 'middle-right-square', 'x.4' : 'bottom-left-square', 'o.2' : 'bottom-middle-square', 'o.3':'bottom-right-square','positive' : 'outcome'},inplace=True)

In [31]:
data.head(4)

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,outcome
0,x,x,x,x,o,o,o,x,o,positive
1,x,x,x,x,o,o,o,o,x,positive
2,x,x,x,x,o,o,o,b,b,positive
3,x,x,x,x,o,o,b,o,b,positive

In [5]:
data_new = pd.get_dummies(data.iloc[:,0:9])

In [41]:
data_new.head(7)

,top left_b,top left_o,top left_x,top middle_b,top middle_o,top middle_x,top right_b,top right_o,top right_x,middle left_b,...,middle right_x,bottom left_b,bottom left_o,bottom left_x,bottom middle_b,bottom middle_o,bottom middle_x,bottom right_b,bottom right_o,bottom right_x
0,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,0,1,0,1,0
1,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,0,0,1
2,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,1,0,0,1,0,0
3,0,0,1,0,0,1,0,0,1,0,...,0,1,0,0,0,1,0,1,0,0
4,0,0,1,0,0,1,0,0,1,0,...,0,1,0,0,1,0,0,0,1,0
5,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,0,1,0,1,0,0
6,0,0,1,0,0,1,0,0,1,0,...,0,0,1,0,1,0,0,0,1,0

In [32]:
data_final = pd.concat([data_new, data.iloc[:,9]],axis=1)

In [33]:
trainSet, testSet = train_test_split(data_final,test_size = 2)

In [35]:
trainSet.head(7)

,top left_b,top left_o,top left_x,top middle_b,top middle_o,top middle_x,top right_b,top right_o,top right_x,middle left_b,...,bottom left_b,bottom left_o,bottom left_x,bottom middle_b,bottom middle_o,bottom middle_x,bottom right_b,bottom right_o,bottom right_x,outcome
903,1,0,0,0,0,1,0,1,0,1,...,0,1,0,0,0,1,1,0,0,negative
579,1,0,0,0,1,0,1,0,0,0,...,1,0,0,0,1,0,1,0,0,positive
572,1,0,0,0,1,0,0,1,0,1,...,0,0,1,0,0,1,0,0,1,positive
878,1,0,0,0,0,1,0,0,1,0,...,0,1,0,0,1,0,0,1,0,negative
472,0,1,0,1,0,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,positive
897,1,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,1,1,0,0,negative
596,1,0,0,1,0,0,0,0,1,0,...,0,0,1,0,1,0,0,0,1,positive

In [36]:
from sklearn.linear_model import LogisticRegression
LogisReg = LogisticRegression()

In [37]:
x_trainSet = trainSet.iloc[:,:-1]
y_trainSet = trainSet.iloc[:,-1]
x_testSet = testSet.iloc[:,:-1]
y_testSet = testSet.iloc[:,-1]
LogisReg = LogisReg.fit(x_trainSet,y_trainSet)

/usr/local/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [39]:
LogisReg.score(x_trainSet, y_trainSet)

0.9832460732984293

In [40]:
from sklearn import metrics
from sklearn.model_selection import cross_val_score
probability = LogisReg.predict_proba(x_testSet)
predicted = LogisReg.predict(x_testSet)

In [19]:
print(metrics.confusion_matrix(y_testSet, predicted))

[[35  2]
 [ 0 59]]